(function(){
  const nav='<div class="demo-nav"><i>⌂<small>Home</small></i><i>☆<small>Learning</small></i><i>▣<small>Course</small></i><i>◫<small>KSB’s</small></i><i>▤<small>Documents</small></i><i>⚙<small>Settings</small></i></div>';
  const screen=(type,focus='')=>{
    const H=x=>`<div class="${focus===x?'demo-focus':''}">`;
    const end='</div>';
    const screens={
      welcome:`<div class="demo-welcome"><img src="logo.png"><b>Apprentice+</b><span>Your Course, Your Way</span></div>`,
      navigation:`<div class="demo-mini-header">Apprentice+</div><div class="demo-placeholder tall">Your current page</div>${focus==='nav'?nav.replace('demo-nav','demo-nav demo-focus'):nav}`,
      home:`<div class="demo-mini-header">Home</div>${H('progress')}<div class="demo-tile"><small>COURSE PROGRESS</small><b>27%</b><div class="demo-bar"><i></i></div></div>${end}${H('next')}<div class="demo-next"><small>WHAT SHOULD I DO NEXT?</small><b>Complete Assignment 4</b><button>Open assignment</button></div>${end}<div class="demo-row"><div>XP & badges</div><div>Rewards</div></div>${nav}`,
      learning:`<div class="demo-mini-header">Learning</div>${['Revision Packs','Functional Skills','CSCS','In-house Training','Learner Notepad'].map((x,i)=>`${H(`learn${i}`)}<div class="demo-list-row"><span>${['📚','∑','⛑','★','✎'][i]}</span><b>${x}</b><i>›</i></div>${end}`).join('')}${nav}`,
      revision:`<div class="demo-mini-header">Revision Pack</div>${H('slides')}<div class="demo-question"><small>TEACHING SLIDE 2 OF 3</small><b>Method and checks</b><p>Read the explanation and worked example before answering the topic question.</p><button class="confirm">Previous　　Next ›</button></div>${end}${nav}`,
      test:`<div class="demo-mini-header">Learning Test</div><div class="demo-question"><small>QUESTION 4 OF 20</small><b>Read the question and choose one answer.</b>${['Answer A','Answer B','Answer C','Answer D'].map(x=>`<button>${x}</button>`).join('')}${H('confirm')}<button class="confirm">Confirm answer</button>${end}</div>${nav}`,
      notes:`<div class="demo-mini-header">Learner Notepad</div>${H('create')}<div class="demo-zone"><small>LEARNER NOTES</small><b>＋ Create a new note</b><p>Save text, dictated notes and reference images.</p></div>${end}${H('saved')}<div class="demo-list-row"><span>✎</span><b>Saved revision note</b><i>›</i></div>${end}${nav}`,
      course:`<div class="demo-mini-header">Course</div><div class="demo-course-tabs">${H('as')}<button class="as">Assignments<b>AS</b></button>${end}<div class="support"><small>SUPPORTING EVIDENCE</small>${['TA','PA','WT','EPA'].map(x=>`${H(x.toLowerCase())}<button>${x}</button>${end}`).join('')}</div></div><div class="demo-workflow">Assignment › TA, PA or WT › Upload ✓</div>${nav}`,
      list:`<div class="demo-mini-header">Assignments</div>${[1,2,3].map((n,i)=>`${H(i===0?'item':'')}<div class="demo-list-row"><span>${n}</span><b>Assignment ${n}: ${['Health & Safety','Safe Systems of Work','Environmental Practice'][i]}</b><i>›</i></div>${end}`).join('')}${nav}`,
      assignment:`<div class="demo-mini-header">Assignment 1</div><div class="demo-tile"><b>Health & Safety</b><small>K1 · K3 · S1 · B1</small></div>${H('photos')}<div class="demo-photo-grid">${[1,2,3,4,5,6].map(n=>`<i>＋<small>Photo ${n}</small></i>`).join('')}</div>${end}${H('prompts')}<div class="demo-prompts"><i>● Safe workspace</i><i>● PPE</i><i>● Risk assessment</i></div>${end}${H('text')}<div class="demo-textarea">Type your activity statement here…</div>${end}${H('complete')}<button class="demo-complete">Complete assignment</button>${end}${nav}`,
      chooser:`<div class="demo-mini-header">Add photo</div><div class="demo-sheet"><b>What this photo should show</b><p>Clear evidence of you completing the required skill.</p>${H('camera')}<button>📷 Take a photo</button>${end}${H('gallery')}<button>🖼 Choose from gallery</button>${end}</div>${nav}`,
      ta:`<div class="demo-mini-header">Trade Academy</div><div class="demo-question"><small>QUESTION 1 OF 10</small><b>Which control should be checked first?</b>${['Answer A','Answer B','Answer C','Answer D'].map(x=>`<button>${x}</button>`).join('')}${H('confirm')}<button class="confirm">Confirm & next</button>${end}</div>${nav}`,
      pa:`<div class="demo-mini-header">Practical Assessment</div><div class="demo-tile"><b>Practical task</b><p>Assessor observes and scores each area.</p></div>${H('marks')}<div class="demo-score-grid">${['Setting out','Accuracy','Quality','Safe working'].map(x=>`<label>${x}<span>1 2 3 4 5</span></label>`).join('')}</div>${end}${H('signature')}<div class="demo-sign">Assessor signature</div>${end}${nav}`,
      wt:`<div class="demo-mini-header">Witness Testimony</div>${H('details')}<div class="demo-input">Witness name and job title</div>${end}${H('statement')}<div class="demo-textarea">Describe exactly what was observed…</div>${end}${H('signature')}<div class="demo-sign">Witness signature</div>${end}${nav}`,
      epa:`<div class="demo-mini-header">EPA Practice</div>${['Knowledge mock · 40 questions','Practical mock · assessor grading','Professional discussion · coach questions'].map((x,i)=>`${H(`epa${i}`)}<div class="demo-list-row"><span>${i+1}</span><b>${x}</b><i>›</i></div>${end}`).join('')}${nav}`,
      documents:`<div class="demo-mini-header">Documents</div>${H('ready')}<div class="demo-zone"><small>READY TO UPLOAD</small><b>Download completed assignment</b><button>Download evidence</button></div>${end}${H('library')}<div class="demo-zone library"><small>DOCUMENT LIBRARY</small><div>AS　TA　PA</div><div>WT　EPA　AC</div></div>${end}${nav}`,
      ksb:`<div class="demo-mini-header">KSB’s</div>${H('gap')}<button class="demo-gap">Show incomplete KSB’s only</button>${end}${['K1 Health & Safety','S1 Safe working','B1 Professional conduct'].map(x=>`<div class="demo-list-row"><b>${x}</b><span>AS · TA/PA · WT</span></div>`).join('')}${nav}`,
      mate:`<div class="demo-mini-header">Apprentice+ Tools</div>${H('tools')}<div class="demo-row"><div>SafeMate</div><div>MeasureMate</div><div>FixMate</div><div>MaterialMate</div><div>QuoteMate</div><div>HintMate</div></div>${end}<div class="demo-tile"><small>UNLOCKED WITH PROGRESS</small><b>Course-specific support</b></div>${nav}`,
      settings:`<div class="demo-mini-header">Settings</div>${['Learner Profile','Reading & Notifications','App, Help & Updates','Developer Mode'].map((x,i)=>`${H(`setting${i}`)}<div class="demo-list-row"><b>${x}</b><i>＋</i></div>${end}`).join('')}${nav}`,
      apphelp:`<div class="demo-mini-header">App, Help & Updates</div>${H('share')}<div class="demo-zone"><small>SHARE APPRENTICE+</small><b>QR code · Share · Website link</b><button>Share Apprentice+</button></div>${end}${H('support')}<div class="demo-zone library"><small>LEARNER SUPPORT</small><div>Demo　FAQs　Feedback　Privacy</div></div>${end}${H('updates')}<div class="demo-zone"><small>APP UPDATES</small><b>Installed and latest version</b><button>Check for updates</button></div>${end}${nav}`,
      recap:`<div class="demo-recap"><b>Your evidence journey</b><span>1　Complete Assignment (AS)</span><i>↓</i><span>2　Add TA, PA or WT</span><i>↓</i><span>3　Download evidence</span><i>↓</i><span>4　Upload to your portfolio</span><i>↓</i><span>5　Tap Uploaded ✓</span></div>`,
      disclaimer:`<div class="demo-disclaimer"><b>Protect and submit your work</b><p>Apprentice+ stores its data and evidence locally on this device. Work completed inside the app is not automatically submitted to your college, provider, employer or online portfolio.</p><p>You must download completed evidence and upload it to the online portfolio specified by your provider. Keep backups and do not clear the app’s data before your evidence is safely uploaded.</p><label><input id="demoDisclaimerCheck" type="checkbox"> I understand that my evidence is stored locally and must be uploaded.</label></div>`
    };return `<div class="demo-phone ${focus?'demo-has-focus':''}">${screens[type]||screens.home}</div>`;
  };
  const full=[
    ['welcome','','Welcome to Apprentice+','This demonstration shows you how to complete assignments, add supporting evidence and prepare files for your online portfolio.'],
    ['navigation','nav','The bottom navigation','These six buttons take you to every main area of Apprentice+. We will look at each one first.'],
    ['home','progress','Home','Home shows assignment progress, the next recommended action, XP, badges, rewards and unlocked Mate tools.'],
    ['learning','','Learning','Learning contains revision packs, Functional Skills, CSCS preparation, in-house training and the Learner Notepad.'],
    ['revision','slides','Revision Packs','Each topic contains three teaching slides and a question. Your place is saved, so you can continue later or restart the pack.'],
    ['test','confirm','Tests and training','Functional Skills, CSCS and in-house activities use question slides. Confirm each answer to continue; passed in-house training creates an acknowledgement certificate.'],
    ['notes','create','Learner Notepad','Create notes for reminders, revision and planning. Notes can contain text, dictation and several images, and saved images open in a full preview.'],
    ['course','','Course','Course contains primary Assignments, supporting TA, PA and WT evidence, plus EPA practice.'],
    ['ksb','gap','KSB’s','The matrix shows completed Knowledge, Skills and Behaviours. The gap finder concentrates on what remains.'],
    ['documents','library','Documents','Ready to Upload prepares evidence bundles. Document Library stores individual PDFs.'],
    ['settings','','Settings','Add your profile, signature and portfolio link, then manage accessibility, notifications and updates.'],
    ['home','next','What Should I Do Next?','This card always leads you to the next assignment action. Tap its button to open the correct place.'],
    ['course','as','Assignments are primary evidence','Tap the large green AS box. An Assignment is always the main evidence for each part of your course.'],
    ['list','item','Choose an assignment','Tap an assignment to begin. Its status changes as you progress through evidence and upload.'],
    ['assignment','','Read the assignment','Check the title, instructions and KSB tags before collecting evidence.'],
    ['assignment','photos','Add six photographs','Tap each photo space. Your photographs should clearly show you personally completing the required work.'],
    ['chooser','gallery','Camera or gallery','Take a new photograph or choose an existing image from your phone gallery.'],
    ['assignment','text','Write your statement','Explain what you did, tools and materials, safe working, checks and problems you solved.'],
    ['assignment','prompts','Turn the prompts green','The required KSB prompts turn green when your statement contains suitable information.'],
    ['assignment','complete','Complete the quality check','Six photos, 100 words, every prompt and your saved signature must be ready before completion.'],
    ['course','ta','Choose one supporting item','After AS, add any one supporting item: TA, PA or WT. You do not need all three.'],
    ['ta','confirm','Trade Academy (TA)','Choose an answer and press Confirm. TA provides Knowledge and Behaviour supporting evidence.'],
    ['pa','marks','Practical Assessment (PA)','An assessor observes the task, scores each area, adds feedback and signs the mark sheet.'],
    ['wt','statement','Witness Testimony (WT)','A suitable workplace witness records what they observed, adds their details and signs it.'],
    ['epa','epa0','EPA knowledge mock','The knowledge mock randomly tests information from across the course KSBs without HintMate support.'],
    ['epa','epa1','EPA practical mock','A tutor or coach grades a demanding trade task and signs the record. Feedback identifies areas that are not yet EPA ready.'],
    ['epa','epa2','EPA professional discussion','A coach asks one challenging assignment-based question at a time using open, probing, hypothetical or direct approaches.'],
    ['documents','ready','Download and upload','Download the completed assignment bundle, upload it to your portfolio, then tap Uploaded ✓ in Apprentice+.'],
    ['documents','library','Document Library','Open AS, TA, PA, WT, EPA or Academy Certificate categories to find saved records. Tap a compact document card to preview and download it.'],
    ['mate','tools','Rewards and Mate tools','Progress unlocks course-specific Mate tools, HintMate allowances, badges, titles and colour themes. Claimed Mate apps appear on Home.'],
    ['settings','setting0','Learner Profile','Save the correct learner name, signature and online portfolio link used by evidence records and upload guidance.'],
    ['settings','setting1','Reading, accessibility and notifications','Choose Easy Read, dyslexia-friendly display, overlays, read-aloud, focus, spelling and dictation support, then control app messages.'],
    ['apphelp','share','Share Apprentice+','Scan the working QR code, use the phone share menu or open and copy the Apprentice+ website link.'],
    ['apphelp','support','Help and local data','Replay this demo, read FAQs, send feedback, view the privacy notice, check storage and download a data backup.'],
    ['apphelp','updates','Install and update','Install Apprentice+ on the phone, check the installed version and read What’s New before downloading an approved update.'],
    ['recap','','Assignment workflow recap','Complete AS, add one of TA, PA or WT, download the files, upload them and confirm Uploaded ✓.'],
    ['disclaimer','','Important information','Your app data remains on this device until you download and upload it. Please confirm that you understand.']
  ];
  const tours={
    home:[['home','progress','Course progress','This percentage is based on completed Assignments. Expand the section for supporting evidence detail.'],['home','next','Your next action','Follow this card to continue the correct assignment workflow.'],['home','','Achievements and tools','Expand the remaining sections to see XP, badges, rewards and Mate apps.']],
    academy:[['learning','learn0','Revision packs','Open Functional Skills or course-assignment revision packs. Every topic provides three teaching slides followed by a question, and unfinished work can be continued later.'],['learning','learn1','Functional Skills','Complete the separate Level 1 and Level 2 Maths and English tests. Read every option, confirm each answer and achieve the stated pass requirement.'],['learning','learn2','CSCS preparation','Choose Easy, Medium or Hard CSCS practice. The levels use different question totals and XP values, with Hard providing the strongest challenge.'],['learning','learn3','In-house training','Read the teaching content before taking each topic test. A successful pass saves an unaccredited participation acknowledgement in Documents.'],['learning','learn4','Learner Notepad','Create and save notes containing typed or dictated text and several reference images. Tap a saved note to reopen it and tap an image for full preview.']],
    revision:[['revision','slides','Teaching and questions','Work through Understand, Method and Applied Example before answering the fourth slide. Previous revisits a slide; Next moves forward after confirmation.']],
    test:[['test','','Question slide','Read the complete question and every possible answer before choosing. Your current place is saved if you leave the activity.'],['test','confirm','Confirm and continue','Selecting an option does not move the slide. Press Confirm answer when satisfied, then read the feedback before continuing.']],
    apprenticeship:[['course','as','Assignments','AS is your primary evidence and the most important place to begin.'],['course','ta','Supporting evidence','Add one TA, PA or WT item after completing the matching Assignment.'],['course','epa','EPA practice','Use the three challenging mocks when preparing for End Point Assessment.']],
    assignment:[['assignment','photos','Photographic evidence','Tap all six spaces to use the camera or gallery.'],['assignment','prompts','KSB prompts','Cover each prompt in your own activity statement until it turns green.'],['assignment','text','Activity statement','Write at least 100 words explaining the full activity.'],['assignment','complete','Complete','Submit only when every quality check has passed.']],
    ta:[['ta','','Question slide','Read the question and every possible answer carefully.'],['ta','confirm','Confirm your answer','Choose an answer, then confirm to move to the next slide.']],
    pa:[['pa','marks','Assessment scores','The assessor scores every generic and skill-specific area.'],['pa','signature','Assessor signature','Feedback, assessor details and a signature are required before saving.']],
    wt:[['wt','details','Witness details','The witness records their identity and workplace role.'],['wt','statement','Observed evidence','They describe what they personally saw the apprentice do.'],['wt','signature','Witness signature','The completed testimony must be signed before saving.']],
    ksb:[['ksb','gap','KSB gap finder','Show only incomplete KSBs when planning the next evidence.'],['ksb','','Evidence markers','Tap an AS, TA, PA or WT marker to open that evidence item.']],
    documents:[['documents','ready','Ready to Upload','Choose a completed assignment to create one evidence ZIP, or download the complete portfolio bundle. The app then explains where the file was saved and how to upload it.'],['documents','library','Document Library','Open AS, TA, PA, WT, EPA or AC, select a compact PDF card, preview the record and use its download option.']],
    settings:[['settings','setting0','Learner Profile','Save your name, signature and online portfolio link. These details are used in evidence records, PDFs and portfolio guidance.'],['settings','setting1','Reading and notifications','Choose reading, dyslexia, focus, spelling and dictation support, then control updates, rewards, encouragement, badges and page information.'],['settings','setting2','App, Help & Updates','Share Apprentice+ by QR, phone share menu or link; replay the demo, read FAQs, send feedback, back up data, install the app and check updates.'],['settings','setting3','Developer Mode','The protected area locks the course after first setup and contains testing, reward override and app-data controls for authorised use.']],
    notepad:[['learning','learn4','Create and save notes','Add a title, text or dictation and up to six images.'],['chooser','gallery','Add images','Choose several gallery images or take a new photograph.']],
    epa:[['epa','epa0','Knowledge mock','Answer the randomised whole-course KSB questions without HintMate. The mock requires the stated pass mark and saves a PDF result.'],['epa','epa1','Practical mock','A tutor or coach scores the demanding trade task from 1 to 3, signs it and saves feedback and a PDF record.'],['epa','epa2','Professional discussion','A coach chooses one approach per assignment, asks the question verbally, records optional final notes and signs the result.']],
    rewards:[['mate','tools','Rewards and Mate apps','Claim earned rewards and open course-specific tools unlocked by assignment progress. Locked apps remain unavailable until their stage is reached or an authorised override is saved.']]
  };
  const briefs={
    home:'Your progress dashboard. It shows completed Assignments, the next required action, XP, badges, rewards and unlocked Mate tools.',
    academy:'Learning contains course and Functional Skills revision packs, Maths and English tests, three CSCS levels, in-house training certificates and the Learner Notepad.',
    revision:'Revision packs use three teaching slides and one question for each topic. Your place is saved so unfinished packs can be continued or restarted.',
    apprenticeship:'Complete an Assignment as primary evidence, add one TA, PA or WT supporting item, then download and upload the evidence.',
    assignment:'Add six relevant photographs and a 100-word activity statement that covers every KSB prompt before completing the Assignment.',
    ta:'Answer the assignment-specific questions to create Knowledge and Behaviour supporting evidence.',
    pa:'An assessor scores and signs a practical task linked to the course Skills.',
    wt:'A workplace witness records and signs what they personally observed the apprentice completing.',
    ksb:'The matrix shows every Knowledge, Skill and Behaviour, its evidence and any remaining gaps.',
    documents:'Prepare evidence for portfolio upload or open individual PDFs from the Document Library.',
    settings:'Manage the learner profile, accessibility, notifications, sharing, help, backups, installation, updates and protected developer controls.',
    notepad:'Create private notes containing text, dictation and reference images stored on this device.',
    epa:'Practise the course-specific EPA knowledge test, practical assessment and professional discussion.',
    rewards:'View unlocked Apprentice+ tools, colour themes and agreed reward cards.'
  };
  function contextKey(){
    if(view.assignment)return'assignment';if(view.revisionPack)return'revision';if(view.academyTest)return'test';if(view.academyModule)return'ta';if(view.practicalAssessment)return'pa';if(view.witnessAssignment)return'wt';if(view.epaMock)return'epa';if(view.rewardApp)return'rewards';if(view.notepad)return'notepad';if(view.tab==='academy')return'academy';if(view.tab==='apprenticeship')return'apprenticeship';return tours[view.tab]?view.tab:'home';
  }
  function detailedSlides(slides){
    const extra={welcome:'Nothing entered in this demonstration affects your real course, XP, badges, evidence or documents. You can move backwards, exit at any time and replay it later from Home or Learner Support in Settings.',navigation:'The selected button receives the bright outline. These controls remain at the bottom of the app, allowing you to move between areas without returning to Home first.',home:'Use the expandable sections to keep Home compact. What Should I Do Next is the most important card because it follows your Assignment, supporting-evidence and portfolio-upload sequence.',learning:'Learning activities develop understanding and confidence. They support the apprenticeship but do not replace the primary photographic and written workplace evidence completed inside Assignments.',course:'Always begin with the large green AS control. TA, PA and WT are supporting routes, while EPA contains challenging practice for the end of the programme.',ksb:'Each evidence marker opens its related activity. Completed rows turn green, while incomplete rows show exactly which evidence still needs attention.',documents:'Downloading creates files on your phone; it does not send them anywhere. Review the bundle and upload it to the portfolio supplied by your training provider.',settings:'The selected course is protected after setup. Check the saved name, signature and portfolio link because these details are used throughout evidence and PDFs.',list:'Status labels distinguish Not started, In progress, Supporting evidence needed, Ready to upload and Uploaded, helping you resume the correct task.',assignment:'Your work saves locally as you type or add images. Check the saved time and never clear app data before downloading and uploading your evidence.',chooser:'Use clear, relevant photographs that visibly demonstrate your own work. Avoid blurred, duplicated or unrelated pictures that do not prove the required skill.',ta:'Only press Confirm after checking the selection. Your place and answers save when you leave, with Continue or Restart offered when you return.',pa:'PA is completed with an assessor, tutor or coach. Every attempt remains available as a PDF, including unsuccessful attempts, so feedback and development remain visible.',wt:'The witness must have personally observed the work. Their testimony should describe what you did, not provide a general character reference or copy your statement.',recap:'The next Assignment starts only after the current one has primary AS evidence, one supporting item and confirmed portfolio upload.',disclaimer:'A completed status means evidence is ready inside Apprentice+. It is submitted only after you download it and upload it to the correct external portfolio.'};
    return slides.map(([type,focus,title,text])=>[type,focus,title,`${text} ${extra[type]||'Follow the highlighted control carefully, read the guidance and check that the information recorded is accurate before continuing to the next step.'} Use Back if you want to review the previous instruction, or Next when you understand the highlighted action.`]);
  }
  function run(slides,isFull=false){
    let index=0;const wrap=document.createElement('div');wrap.className='guided-demo-overlay';document.body.appendChild(wrap);
    const paint=()=>{const [type,focus,title,text]=slides[index],last=index===slides.length-1;wrap.innerHTML=`<div class="guided-demo-shell"><div class="demo-top"><b>${isFull?'APPRENTICE+ GUIDED DEMO':'PAGE DEMO'}</b><button id="exitGuidedDemo">×</button></div><div class="demo-progress"><i style="width:${(index+1)/slides.length*100}%"></i></div><div class="demo-stage">${screen(type,focus)}<div class="demo-speech"><small>${index+1} OF ${slides.length}</small><h2>${title}</h2><p>${text}</p></div></div><div class="demo-controls"><button id="demoBack" ${index===0?'disabled':''}>‹ Back</button><button id="demoNext" ${last&&type==='disclaimer'?'disabled':''}>${last?'Finish':'Next ›'}</button></div></div>`;$('#exitGuidedDemo',wrap).onclick=()=>wrap.remove();$('#demoBack',wrap).onclick=()=>{index--;paint()};const next=$('#demoNext',wrap);if(type==='disclaimer'){$('#demoDisclaimerCheck',wrap).onchange=e=>next.disabled=!e.target.checked}next.onclick=()=>{if(last){if(isFull){state.demoCompleted=true;state.demoDisclaimerAccepted=true;save()}wrap.remove();if(isFull)toast('Demo completed')}else{index++;paint()}}};
    paint();
  }
  window.openFullAppDemo=()=>run(detailedSlides(full),true);
  window.openPageDemo=()=>run(detailedSlides(tours[contextKey()]||tours.home),false);
  window.showPageInformation=function(title){
    const key=contextKey(),wrap=document.createElement('div');wrap.className='modal-wrap app-notification-wrap';wrap.innerHTML=`<div class="modal-card page-information-modal brief-page-info"><div class="page-information-icon">i</div><small>WHAT’S THIS PAGE ABOUT?</small><h3>${esc(title)}</h3><p>${esc(briefs[key]||'This page helps you record, understand or manage your apprenticeship progress.')}</p><div class="brief-info-actions"><button class="btn btn-secondary" id="closeBriefInfo">OK, got it</button><button class="btn btn-primary" id="startPageDemo">Show me around</button></div></div>`;document.body.appendChild(wrap);$('#closeBriefInfo',wrap).onclick=()=>wrap.remove();$('#startPageDemo',wrap).onclick=()=>{wrap.remove();openPageDemo()};
  };
  const modal=(title,body)=>{const wrap=document.createElement('div');wrap.className='modal-wrap app-notification-wrap';wrap.innerHTML=`<div class="modal-card support-modal"><button class="document-modal-close" aria-label="Close">×</button><small>APPRENTICE+ SUPPORT</small><h3>${title}</h3>${body}</div>`;document.body.appendChild(wrap);$('.document-modal-close',wrap).onclick=()=>wrap.remove();wrap.onclick=e=>{if(e.target===wrap)wrap.remove()};return wrap};
  window.showLearnerHelp=()=>modal('Help & frequently asked questions',`<details open><summary>How do I complete an assignment?</summary><p>Add six relevant photographs, write at least 100 words, cover every green prompt and save your signature.</p></details><details><summary>What supporting evidence do I need?</summary><p>Complete one matching TA, PA or WT item after the primary Assignment.</p></details><details><summary>Has my work been submitted automatically?</summary><p>No. Download the completed assignment and upload it to the online portfolio provided by your college or training provider.</p></details><details><summary>Where is my work saved?</summary><p>App data and images are stored locally on this device. Do not clear site data or uninstall before downloading and uploading your evidence.</p></details><details><summary>How do I continue a test?</summary><p>Question activities save their place. Reopen the activity and select Continue or Restart.</p></details><button class="btn btn-primary replay-help-demo">Replay guided demo</button>`);
  window.showPrivacyNotice=()=>modal('Privacy & local data',`<p>Apprentice+ stores learner details, signatures, evidence images, statements, progress, test answers, notes and settings locally on this device.</p><p>The app does not automatically submit evidence to a college, training provider, employer or portfolio. Learners must download and upload their completed evidence themselves.</p><p>Protect access to the device, download regular backups and do not clear browser/app data or uninstall Apprentice+ until all evidence has been safely uploaded.</p><p>Developer Mode contains export and reset controls. Reset permanently removes locally stored app data.</p><button class="btn btn-primary close-privacy">OK, I understand</button>`);
  window.showFeedbackForm=()=>{const wrap=modal('Send feedback',`<label>What happened or what would help?<textarea id="feedbackText" rows="6" placeholder="Describe the page, button or problem…"></textarea></label><label>Feedback type<select id="feedbackType"><option>Problem</option><option>Suggestion</option><option>Question</option></select></label><button class="btn btn-primary" id="shareFeedback">Share feedback report</button><p class="muted">The report includes the app version, selected course and current page, but not your evidence.</p>`);$('#shareFeedback',wrap).onclick=async()=>{const detail=$('#feedbackText',wrap).value.trim();if(!detail)return toast('Describe the feedback first');const report=`Apprentice+ feedback\nType: ${$('#feedbackType',wrap).value}\nVersion: ${APP_VERSION}\nCourse: ${course().name}\nPage: ${view.tab}\n\n${detail}`;if(navigator.share)await navigator.share({title:'Apprentice+ feedback',text:report});else{await navigator.clipboard?.writeText(report);toast('Feedback report copied')}}};
  window.openSubmissionChecklist=function(a,c,onReady){
    const asDone=!!state.completed[`${c.id}-${a.number}`],ta=!!state.academyPassed[`${c.id}-AT${a.number}`],pa=!!state.practicalAssessments[`${c.id}-PA${a.number}`]?.passed,wt=!!state.witnessTestimonies[`${c.id}-WT${a.number}`]?.completed,support=ta||pa||wt;
    const wrap=modal('Check before downloading',`<p>Review Assignment ${a.number}: <b>${esc(a.title)}</b> before creating the upload bundle.</p><div class="submission-checks"><span class="ok">✓ Correct assignment selected</span><span class="${asDone?'ok':'missing'}">${asDone?'✓':'!'} AS primary evidence completed</span><span class="${support?'ok':'missing'}">${support?'✓':'!'} Supporting evidence included: ${[ta?'TA':'',pa?'PA':'',wt?'WT':''].filter(Boolean).join(', ')||'none'}</span><span class="ok">✓ PDFs ready to generate</span><span class="${state.onlinePortfolioUrl?'ok':'warning'}">${state.onlinePortfolioUrl?'✓':'!'} ${state.onlinePortfolioUrl?'Portfolio link saved':'Portfolio link not saved—add it in Settings'}</span></div><label class="review-confirm"><input id="evidenceReviewed" type="checkbox"> I have reviewed the photographs, statement, supporting evidence and learner details.</label><button class="btn btn-primary" id="confirmEvidenceDownload" disabled>Generate PDFs and download ZIP</button>`);
    const review=$('#evidenceReviewed',wrap),button=$('#confirmEvidenceDownload',wrap);review.onchange=()=>button.disabled=!review.checked||!asDone||!support;button.onclick=()=>{wrap.remove();onReady()};
  };
  window.updateStorageMonitor=async function(){
    const box=$('#storageMonitor');if(!box)return;const raw=new Blob([localStorage.getItem('applus-state')||'']).size,images=Object.values(state.drafts||{}).reduce((n,d)=>n+(d.photos||[]).filter(Boolean).length,0)+(state.learnerNotes||[]).reduce((n,d)=>n+(d.images||[]).length,0);let used=raw,quota=0;try{const estimate=await navigator.storage?.estimate();used=Math.max(used,estimate?.usage||0);quota=estimate?.quota||0}catch{}const pct=quota?Math.round(used/quota*100):0,level=pct>=80?'action':pct>=60?'warning':'good',label=level==='action'?'Action required':level==='warning'?'Getting full':'Good';box.className=`storage-monitor ${level}`;box.innerHTML=`<small>LOCALLY STORED APP DATA</small><div><b>${(used/1048576).toFixed(1)} MB used · ${images} saved image${images===1?'':'s'}</b><span>${label}</span></div><div class="storage-bar"><i style="width:${Math.max(2,pct)}%"></i></div><p>${quota?`${pct}% of the storage allowance currently reported to Apprentice+.`:'Your browser did not provide a storage allowance, so only known Apprentice+ data is shown.'} ${level==='good'?'Continue making regular backups.':'Download a backup and upload completed evidence before adding more images.'}</p>`;
  };
  window.openPracticeAssignment=function(){
    let step=0,photos=0,text='',support='',uploaded=false;const wrap=document.createElement('div');wrap.className='guided-demo-overlay practice-overlay';document.body.appendChild(wrap);
    const prompts=()=>[['PPE',/ppe/i],['safe workspace',/safe workspace/i],['quality checks',/quality|check/i]].map(([name,re])=>({name,hit:re.test(text)})),ready=()=>photos===6&&text.trim().split(/\s+/).filter(Boolean).length>=30&&prompts().every(x=>x.hit);
    const paint=()=>{const stages=[
      `<div class="practice-intro"><img src="logo.png"><h2>Demo Assignment</h2><p>Practise the full evidence process safely. Nothing here changes your course progress, KSBs, XP, badges or documents.</p><div class="practice-safe">SAFE PRACTICE AREA</div></div>`,
      `<div><small>STEP 1 · PHOTOGRAPHS</small><h2>Add six demonstration photos</h2><p>Tap every space. The demo fills it with a sample image marker—your camera and gallery will not open.</p><div class="practice-photo-grid">${Array.from({length:6},(_,i)=>`<button data-practice-photo="${i}" class="${i<photos?'added':''}">${i<photos?'✓':'＋'}<small>Photo ${i+1}</small></button>`).join('')}</div><b>${photos}/6 added</b></div>`,
      `<div><small>STEP 2 · ACTIVITY STATEMENT</small><h2>Cover the prompts</h2><p>Write at least 30 practice words and include PPE, safe workspace and quality checks. This shorter limit is only for the demonstration.</p><div class="practice-prompts">${prompts().map(x=>`<span class="${x.hit?'ok':''}">${x.hit?'✓':'○'} ${x.name}</span>`).join('')}</div><textarea id="practiceText" rows="8" placeholder="For example: I prepared a safe workspace and selected the correct PPE…">${esc(text)}</textarea><b>${text.trim()?text.trim().split(/\s+/).length:0}/30 practice words</b></div>`,
      `<div><small>STEP 3 · QUALITY CHECK</small><h2>Is the Assignment ready?</h2><div class="submission-checks"><span class="${photos===6?'ok':'missing'}">${photos===6?'✓':'!'} Six photographs</span><span class="${text.trim().split(/\s+/).filter(Boolean).length>=30?'ok':'missing'}">${text.trim().split(/\s+/).filter(Boolean).length>=30?'✓':'!'} Practice word count</span><span class="${prompts().every(x=>x.hit)?'ok':'missing'}">${prompts().every(x=>x.hit)?'✓':'!'} Every prompt green</span></div><p>${ready()?'Your demonstration Assignment is ready. In real coursework, completing AS awards progress and a badge.':'Go Back and finish the missing practice evidence.'}</p></div>`,
      `<div><small>STEP 4 · SUPPORTING EVIDENCE</small><h2>Choose one supporting route</h2><p>Select any one. A real TA is a questionnaire, PA is assessor-marked practical evidence, and WT is completed by a workplace witness.</p><div class="practice-support">${['TA','PA','WT'].map(x=>`<button data-practice-support="${x}" class="${support===x?'selected':''}">${x}<small>${x==='TA'?'Knowledge & Behaviour':x==='PA'?'Practical Skills':'Workplace witness'}</small></button>`).join('')}</div></div>`,
      `<div><small>STEP 5 · PORTFOLIO</small><h2>Download, upload and confirm</h2><div class="practice-upload-flow"><button class="done">✓ Demo evidence bundle prepared</button><button class="done">✓ Online portfolio opened</button><button id="practiceUploaded" class="${uploaded?'done':''}">${uploaded?'✓ Uploaded':'Tap to confirm Uploaded'}</button></div><p>This simulation creates no files. In a real Assignment, check the ZIP, upload it to your provider’s portfolio and only then confirm Uploaded ✓.</p></div>`,
      `<div class="practice-intro"><div class="practice-complete">✓</div><h2>Practice complete</h2><p>You have practised primary AS evidence, one supporting item and the portfolio-upload confirmation. You are ready to begin a real Assignment.</p><button class="btn btn-primary" id="startRealAssignment">Start my first assignment</button></div>`
    ];wrap.innerHTML=`<div class="guided-demo-shell"><div class="demo-top"><b>SAFE DEMO ASSIGNMENT</b><button id="exitPractice">×</button></div><div class="demo-progress"><i style="width:${(step+1)/stages.length*100}%"></i></div><div class="practice-stage">${stages[step]}</div><div class="demo-controls"><button id="practiceBack" ${step===0?'disabled':''}>‹ Back</button><button id="practiceNext" ${step===stages.length-1?'disabled':''}>${step===stages.length-2?'Finish practice':step===0?'Begin ›':'Next ›'}</button></div></div>`;$('#exitPractice',wrap).onclick=()=>wrap.remove();$('#practiceBack',wrap).onclick=()=>{step--;paint()};$$('[data-practice-photo]',wrap).forEach(b=>b.onclick=()=>{photos=Math.max(photos,Number(b.dataset.practicePhoto)+1);paint()});if($('#practiceText',wrap))$('#practiceText',wrap).oninput=e=>{text=e.target.value;const pos=e.target.selectionStart;paint();const t=$('#practiceText',wrap);t.focus();t.setSelectionRange(pos,pos)};$$('[data-practice-support]',wrap).forEach(b=>b.onclick=()=>{support=b.dataset.practiceSupport;paint()});if($('#practiceUploaded',wrap))$('#practiceUploaded',wrap).onclick=()=>{uploaded=true;paint()};if($('#startRealAssignment',wrap))$('#startRealAssignment',wrap).onclick=()=>{wrap.remove();view.tab='apprenticeship';view.apprenticeshipTab='assignments';view.assignment=course().assignments[0].number;save();render()};$('#practiceNext',wrap).onclick=()=>{if(step===1&&photos<6)return toast('Tap all six demonstration photo spaces');if(step===2&&!ready())return toast('Add 30 words and turn all three prompts green');if(step===3&&!ready())return toast('The practice Assignment is not ready');if(step===4&&!support)return toast('Choose TA, PA or WT');if(step===5&&!uploaded)return toast('Confirm the simulated portfolio upload');step++;paint()}};
    wrap.addEventListener('input',e=>{if(e.target.id!=='practiceText')return;e.stopImmediatePropagation();text=e.target.value;const current=prompts(),words=text.trim()?text.trim().split(/\s+/).length:0;$$('.practice-prompts span',wrap).forEach((span,i)=>{span.classList.toggle('ok',current[i].hit);span.textContent=`${current[i].hit?'✓':'○'} ${current[i].name}`});const count=$('.practice-stage>div>b:last-child',wrap);if(count)count.textContent=`${words}/30 practice words`},true);
    paint();
  };
  window.showDownloadLocation=function(filename){
    const portfolioUrl=/^https?:\/\//i.test(state.onlinePortfolioUrl||'')?state.onlinePortfolioUrl:'';
    const portfolioAction=portfolioUrl?`<a class="btn btn-primary open-online-portfolio" href="${esc(portfolioUrl)}" target="_blank" rel="noopener">Open online portfolio</a>`:'<button class="btn btn-primary add-portfolio-link">Add portfolio link in Settings</button>';
    const wrap=modal('Download saved',`<div class="download-location"><span>⇩</span><div><small>FILE NAME</small><b>${esc(filename||'Apprentice+ file')}</b><p>Your browser normally saves this in the phone’s <b>Downloads</b> folder. The exact folder can depend on your browser’s download settings.</p></div></div><div class="portfolio-upload-help"><small>NEXT · UPLOAD YOUR EVIDENCE</small><h3>Add this file to your online portfolio</h3><ol><li>Open your phone’s <b>Files</b> or <b>My Files</b> app and choose <b>Downloads</b>.</li><li>Check that the filename shown above is there.</li><li>Open your online portfolio using the button below and sign in.</li><li>Open the correct assignment or evidence area and choose its upload or add-file option.</li><li>Select the downloaded ZIP. If your portfolio does not accept ZIP files, extract it and upload the PDFs inside.</li><li>Wait for the upload to finish, check the files are attached, then save or submit them.</li><li>Return to Apprentice+ and mark the assignment as <b>Uploaded ✓</b>.</li></ol><p>Portfolio screens and button names vary between providers, including Aptem.</p></div>${portfolioAction}<button class="btn btn-secondary close-download-location">Close</button>`);
    $('.close-download-location',wrap).onclick=()=>wrap.remove();
    const addLink=$('.add-portfolio-link',wrap);
    if(addLink)addLink.onclick=()=>{wrap.remove();view.tab='settings';save();render();setTimeout(()=>$('.portfolio-profile-field')?.scrollIntoView({behavior:'smooth',block:'center'}),150)};
  };
  if(!HTMLAnchorElement.prototype.__appPlusDownloadNotice){const originalClick=HTMLAnchorElement.prototype.click;HTMLAnchorElement.prototype.click=function(){const filename=this.download;originalClick.call(this);if(filename)setTimeout(()=>showDownloadLocation(filename),450)};HTMLAnchorElement.prototype.__appPlusDownloadNotice=true}
  document.addEventListener('click',e=>{if(e.target.closest('.replay-help-demo')){e.target.closest('.modal-wrap')?.remove();openFullAppDemo()}if(e.target.closest('.close-privacy'))e.target.closest('.modal-wrap')?.remove()});
})();
