(function(){
  const notes=()=>state.learnerNotes=state.learnerNotes||[];
  const dateText=value=>new Date(value||Date.now()).toLocaleString('en-GB',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});
  function noteById(id){return notes().find(x=>String(x.id)===String(id))}
  function openNoteImageChooser(remaining,onPicked){
    const wrap=document.createElement('div');wrap.className='modal-wrap note-image-chooser';wrap.innerHTML=`<div class="modal-card"><div class="modal-grip"></div><span class="eyebrow">ADD TO NOTE</span><h3>Add images</h3><p class="muted">Choose up to ${remaining} image${remaining===1?'':'s'} at once from the gallery, or take a new photograph.</p><button class="choice note-camera">📷 <span><b>Take a photo</b><small>Open the phone camera</small></span></button><button class="choice note-gallery">🖼️ <span><b>Choose multiple images</b><small>Select several gallery images together</small></span></button><div class="note-image-status" hidden>Preparing images…</div><button class="modal-cancel">Cancel</button><input class="note-camera-input" type="file" accept="image/*" capture="environment" hidden><input class="note-gallery-input" type="file" accept="image/*" multiple hidden></div>`;document.body.appendChild(wrap);
    const status=$('.note-image-status',wrap),close=()=>wrap.remove(),process=async files=>{files=[...files].slice(0,remaining);if(!files.length)return;status.hidden=false;try{const output=[];for(const file of files)output.push(await compressPhoto(file));close();onPicked(output)}catch(e){status.textContent=e.message||'The images could not be added.'}};
    $('.note-camera',wrap).onclick=()=>$('.note-camera-input',wrap).click();$('.note-gallery',wrap).onclick=()=>$('.note-gallery-input',wrap).click();$('.note-camera-input',wrap).onchange=e=>process(e.target.files);$('.note-gallery-input',wrap).onchange=e=>process(e.target.files);$('.modal-cancel',wrap).onclick=close;wrap.onclick=e=>{if(e.target===wrap)close()};
  }
  function saveEditorNote(){
    const title=$('#learnerNoteTitle')?.value.trim()||'',text=$('#learnerNoteText')?.value.trim()||'',existing=noteById(view.learnerNote),images=existing?.images||[];
    if(!title&&!text&&!images.length)return null;
    const now=new Date().toISOString(),note=existing||{id:String(Date.now()),created:now,images:[]};note.title=title||'Untitled note';note.text=text;note.updated=now;if(!existing)notes().unshift(note);view.learnerNote=note.id;save();return note;
  }
  window.renderLearnerNotepad=function(){
    const list=notes();
    shell('Learner Notepad',`<button class="back" id="backFromNotepad">‹ Back to Documents</button><div class="notepad-hero"><div class="notepad-hero-copy"><span>LEARNER NOTEPAD</span><h2>Capture it. Keep it.</h2><p>Save course notes, site reminders, measurements and reference images in one place.</p></div><button class="notepad-new-button" id="createLearnerNote"><span>＋</span><b>New note</b></button></div><div class="notepad-section-head"><div><span>${list.length}</span><b>Saved notes</b></div><small>Newest first</small></div><div class="learner-note-list">${list.length?list.map(n=>`<button class="learner-note-card" data-open-note="${n.id}">${n.images?.[0]?`<img class="note-card-thumb" src="${n.images[0]}" alt="">`:`<div class="note-card-icon">✎</div>`}<div class="note-card-copy"><div class="note-card-meta"><small>${dateText(n.updated)}</small>${n.images?.length?`<em>▧ ${n.images.length}</em>`:''}</div><h3>${esc(n.title||'Untitled note')}</h3><p>${esc((n.text||'No written text').slice(0,115))}${(n.text||'').length>115?'…':''}</p></div><span class="note-card-arrow">›</span></button>`).join(''):'<div class="notepad-empty"><span>✎</span><b>Your notepad is ready</b><p>Create your first note and add text or images.</p></div>'}</div>`);
    $('#backFromNotepad').onclick=()=>{view.notepad=false;view.learnerNote=null;render()};$('#createLearnerNote').onclick=()=>{view.learnerNote='new';renderLearnerNoteEditor()};$$('[data-open-note]').forEach(b=>b.onclick=()=>{view.learnerNote=b.dataset.openNote;renderLearnerNoteEditor()});
  };
  window.renderLearnerNoteEditor=function(){
    let note=view.learnerNote==='new'?null:noteById(view.learnerNote);if(view.learnerNote!=='new'&&!note){view.learnerNote=null;return renderLearnerNotepad()}const images=note?.images||[];
    shell(note?'Edit Note':'New Note',`<button class="back" id="backFromNoteEditor">‹ Back to Notepad</button><div class="note-editor-shell"><div class="note-editor-top"><span>${note?'EDIT SAVED NOTE':'NEW NOTE'}</span><h2>${note?'Update your note':'What do you need to remember?'}</h2><p>Use text, dictation and images together.</p></div><div class="learner-note-editor"><label><span>Title</span><input id="learnerNoteTitle" type="text" maxlength="100" placeholder="e.g. Cavity wall measurements" value="${esc(note?.title||'')}"></label><label><span>Notes</span><textarea id="learnerNoteText" spellcheck="true" autocorrect="on" autocapitalize="sentences" placeholder="Type or dictate your notes here…">${esc(note?.text||'')}</textarea></label><div class="note-image-heading"><div><b>Images</b><small>${images.length} of 6 added · tap an image to preview</small></div><button type="button" id="addNoteImage" ${images.length>=6?'disabled':''}>＋ Add images</button></div><div class="note-image-grid">${images.map((src,i)=>`<figure data-preview-note-image="${i}" role="button" tabindex="0" aria-label="Preview note image ${i+1}"><img src="${src}" alt="Note image ${i+1}"><span>${i+1}</span><button type="button" data-remove-note-image="${i}" aria-label="Remove image">×</button></figure>`).join('')}${images.length?'':'<button type="button" class="note-image-placeholder" id="emptyNoteImageAdd"><span>＋</span><b>Add photos or reference images</b><small>Camera or multi-select gallery</small></button>'}</div><div class="note-editor-actions"><button class="btn btn-primary" id="saveLearnerNote">Save note</button>${note?'<button class="btn btn-danger" id="deleteLearnerNote">Delete</button>':''}</div><p class="muted note-save-date">${note?`Last saved ${dateText(note.updated)}`:'Saved privately on this device.'}</p></div></div>`);
    const ensureDraft=()=>{if(!note){note={id:String(Date.now()),title:'',text:'',images:[],created:new Date().toISOString(),updated:new Date().toISOString()};notes().unshift(note);view.learnerNote=note.id}note.title=$('#learnerNoteTitle').value;note.text=$('#learnerNoteText').value;return note};
    $('#backFromNoteEditor').onclick=()=>{saveEditorNote();view.learnerNote=null;renderLearnerNotepad()};$('#saveLearnerNote').onclick=()=>{const saved=saveEditorNote();if(!saved)return toast('Add a title, note or image first');view.notepad=true;view.learnerNote=null;toast('Note saved');renderLearnerNotepad()};
    const addImages=()=>openNoteImageChooser(6-images.length,sources=>{const draft=ensureDraft();draft.images.push(...sources.slice(0,6-draft.images.length));draft.updated=new Date().toISOString();save();renderLearnerNoteEditor()});$('#addNoteImage').onclick=addImages;if($('#emptyNoteImageAdd'))$('#emptyNoteImageAdd').onclick=addImages;
    $$('[data-preview-note-image]').forEach(f=>{const preview=()=>{const src=images[Number(f.dataset.previewNoteImage)],wrap=document.createElement('div');wrap.className='note-preview-wrap';wrap.innerHTML=`<div class="note-preview-toolbar"><b>Image ${Number(f.dataset.previewNoteImage)+1} of ${images.length}</b><button type="button" aria-label="Close full image">×</button></div><img src="${src}" alt="Full-size note image">`;document.body.appendChild(wrap);const close=()=>wrap.remove();$('button',wrap).onclick=close;wrap.onclick=e=>{if(e.target===wrap)close()}};f.onclick=e=>{if(!e.target.closest('[data-remove-note-image]'))preview()};f.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();preview()}}});
    $$('[data-remove-note-image]').forEach(b=>b.onclick=e=>{e.stopPropagation();const draft=ensureDraft();draft.images.splice(Number(b.dataset.removeNoteImage),1);draft.updated=new Date().toISOString();save();renderLearnerNoteEditor()});
    if($('#deleteLearnerNote'))$('#deleteLearnerNote').onclick=()=>{if(confirm('Delete this note and all of its saved images?')){state.learnerNotes=notes().filter(x=>x.id!==note.id);save();view.learnerNote=null;toast('Note deleted');renderLearnerNotepad()}};
    if(window.applyAccessibilitySupport)applyAccessibilitySupport();
  };
})();
